<?php
/**
 * Created by PhpStorm.
 * User: Arielb
 * Date: 11/24/2016
 * Time: 4:02 PM
 */

namespace relbraun\yii2repeater;


use yii\base\Model;
use yii\base\Widget;
use yii\db\ActiveRecord;
use yii\helpers\Json;
use yii\widgets\ActiveForm;

class Repeater extends Widget
{

    /**
     * @var ActiveRecord[]
     */
    public $models;
    /**
     * @var string The view path to render repeater
     */
    public $modelView;
    /**
     * @var string The new item action url to run in ajax
     */
    public $appendAction;
    /**
     * @var string The remove item action url to run in ajax
     */
    public $removeAction;
    /**
     * @var ActiveForm Optional, if you want to use the $form variable.
     */
    public $form;
    /**
     * @var array Key - value params to append to the view file
     */
    public $additionalData = [];


    public function init()
    {
        parent::init(); // TODO: Change the autogenerated stub

    }

    public function run()
    {
        $view = $this->getView();
        RepeaterAsset::register($view);
        $data = Json::encode(['append' => $this->appendAction, 'remove' => $this->removeAction]);
        echo "<div class='ab-repeater'>";
        echo "<div class='list-area'>";
        foreach($this->models as $k => $model){
            $content = $this->render($this->modelView, array_merge(['model' => $model, 'form' => $this->form,], $this->additionalData));
            echo $this->render('repeater', ['content' => $content, 'model' => $model, 'k' => $k]);
        }
        echo "</div><a class='btn btn-primary new-repeater' href='javascript:;'>add new</a><a href='javascript:;' class='btn btn-success recover-btn'>Recover</a></div>";
        $js = "new window.repeater($data)";
        $this->view->registerJs($js);
    }
}
